version = 1

test_patterns = ["src/**"]

exclude_patterns = [
  "HELP.md",
  ".gradle",
  "build/",
  "!gradle/wrapper/gradle-wrapper.jar",
  "!**/src/main/**/build/",
  "!**/src/test/**/build/",
  ".apt_generated",
  ".classpath",
  ".factorypath",
  ".project",
  ".settings",
  ".springBeans",
  ".sts4-cache",
  "bin/",
  "!**/src/main/**/bin/",
  "!**/src/test/**/bin/",
  ".idea",
  "*.iws",
  "*.iml",
  "*.ipr",
  "out/",
  "!**/src/main/**/out/",
  "!**/src/test/**/out/",
  "/nbproject/private/",
  "/nbbuild/",
  "/dist/",
  "/nbdist/",
  "/.nb-gradle/",
  ".vscode/"
]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"