insert into sections (teacher, room, strand, grade_level, section_name) values (415, 'Helogale undulata', 4, 8, 'Arly Capponer');
insert into sections (teacher, room, strand, grade_level, section_name) values (212, 'Lutra canadensis', 9, 9, 'Sherlocke Elsley');
insert into sections (teacher, room, strand, grade_level, section_name) values (649, 'Pavo cristatus', 10, 3, 'Teodorico von Nassau');
insert into sections (teacher, room, strand, grade_level, section_name) values (660, 'Graspus graspus', 6, 11, 'Annemarie Copnall');
insert into sections (teacher, room, strand, grade_level, section_name) values (314, 'Trachyphonus vaillantii', 5, 7, 'Yevette Fidelus');
insert into sections (teacher, room, strand, grade_level, section_name) values (295, 'Stenella coeruleoalba', 11, 4, 'Jane Goley');
insert into sections (teacher, room, strand, grade_level, section_name) values (708, 'Vulpes vulpes', 7, 3, 'Adan Rickards');
insert into sections (teacher, room, strand, grade_level, section_name) values (849, 'Ammospermophilus nelsoni', 11, 6, 'Bank Candwell');
insert into sections (teacher, room, strand, grade_level, section_name) values (806, 'Cercopithecus aethiops', 10, 3, 'Gonzalo Bedell');
insert into sections (teacher, room, strand, grade_level, section_name) values (664, 'Ictalurus furcatus', 3, 12, 'Mariel Leser');
insert into sections (teacher, room, strand, grade_level, section_name) values (417, 'Conolophus subcristatus', 11, 2, 'Thomasa Scawen');
insert into sections (teacher, room, strand, grade_level, section_name) values (809, 'Prionace glauca', 3, 10, 'Brig Rubinsztein');
insert into sections (teacher, room, strand, grade_level, section_name) values (344, 'Macropus rufogriseus', 1, 10, 'Domini Bleakley');
insert into sections (teacher, room, strand, grade_level, section_name) values (406, 'Felis silvestris lybica', 10, 9, 'Barr Rollin');
insert into sections (teacher, room, strand, grade_level, section_name) values (751, 'Centrocercus urophasianus', 9, 2, 'Elisha Packington');
insert into sections (teacher, room, strand, grade_level, section_name) values (345, 'Felis concolor', 2, 5, 'Ediva Aitken');
insert into sections (teacher, room, strand, grade_level, section_name) values (41, 'Ciconia ciconia', 2, 7, 'Norah Chinery');
insert into sections (teacher, room, strand, grade_level, section_name) values (657, 'Pitangus sulphuratus', 1, 3, 'Fairlie Duffy');
insert into sections (teacher, room, strand, grade_level, section_name) values (304, 'Otocyon megalotis', 8, 8, 'Minetta McDarmid');
insert into sections (teacher, room, strand, grade_level, section_name) values (388, 'Salvadora hexalepis', 11, 10, 'Rodi Drysdell');
insert into sections (teacher, room, strand, grade_level, section_name) values (909, 'Semnopithecus entellus', 1, 12, 'Tristam Seiffert');
insert into sections (teacher, room, strand, grade_level, section_name) values (154, 'Fratercula corniculata', 5, 4, 'Abbe Yegorkin');
insert into sections (teacher, room, strand, grade_level, section_name) values (297, 'Ciconia ciconia', 5, 10, 'Estevan Ivakin');
insert into sections (teacher, room, strand, grade_level, section_name) values (685, 'Sarcophilus harrisii', 1, 5, 'Quint Campanelle');
insert into sections (teacher, room, strand, grade_level, section_name) values (261, 'Hystrix cristata', 7, 3, 'Meggie Fellos');